name: Jest Tests

on: [push]

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Jest
        run: npm ci && npm test